# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='question content'),
        ),
    ]
