# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20160513_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 13, 8, 54, 27, 992159, tzinfo=utc), verbose_name='create time'),
        ),
    ]
