# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 13:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0006_auto_20160515_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.FileField(upload_to='uploads/log/%Y/%m/%d/', verbose_name='exam log')),
                ('project', models.FileField(upload_to='uploads/project/%Y/%m/%d/', verbose_name='exam project')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam', verbose_name='exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 15, 13, 7, 9, 726363, tzinfo=utc), verbose_name='create time'),
        ),
    ]
