# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-19 13:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_auto_20160911_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprojects',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 19, 13, 37, 31, 708746, tzinfo=utc), verbose_name='create time'),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 19, 13, 37, 31, 706649, tzinfo=utc), verbose_name='create time'),
        ),
    ]
