# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-18 04:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_auto_20160919_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='isPrivate',
            field=models.BooleanField(default=False, verbose_name='is private?'),
        ),
        migrations.AlterField(
            model_name='examprojects',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 18, 4, 52, 33, 618504, tzinfo=utc), verbose_name='create time'),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 18, 4, 52, 33, 616340, tzinfo=utc), verbose_name='create time'),
        ),
    ]
