# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-02 08:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0010_auto_20161018_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, verbose_name='mac')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam', verbose_name='exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='examprojects',
            name='browser',
            field=models.FileField(default='uploads/default_browser.txt', upload_to='uploads/project/%Y/%m/%d/', verbose_name='exam browser file'),
        ),
        migrations.AddField(
            model_name='examprojects',
            name='has_browser',
            field=models.BooleanField(default=False, verbose_name='has browser file'),
        ),
        migrations.AddField(
            model_name='examprojects',
            name='has_monitor',
            field=models.BooleanField(default=False, verbose_name='has monitor file'),
        ),
        migrations.AddField(
            model_name='examprojects',
            name='monitor',
            field=models.FileField(default='uploads/default_monitor.txt', upload_to='uploads/project/%Y/%m/%d/', verbose_name='exam monitor file'),
        ),
        migrations.AlterField(
            model_name='examprojects',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 8, 29, 49, 816921, tzinfo=utc), verbose_name='create time'),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 8, 29, 49, 810050, tzinfo=utc), verbose_name='create time'),
        ),
    ]
